### ISSUE TITLE
KeyError: 'measurement_date_electricity' / ValueError: ...

### ISSUE THREAD

**Issue by eelcohn** [barisdemirdelen/homeassistant-greenchoice#16]
Hi,

Since some time this component won't start on my Home Assistant setup. It used to work correctly some time ago, but now I get these errors:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:724
integration: Sensor (documentation, issues)
First occurred: 21:18:31 (5 occurrences)
Last logged: 21:18:31

greenchoice: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/sensor.py", line 157, in update
    self._measurement_date = api_result[self._measurement_date_key]
                             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'measurement_date_electricity'
```
...and...
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:909
integration: Sensor (documentation, issues)
First occurred: 21:38:06 (7 occurrences)
Last logged: 21:38:06

Error adding entity sensor.greenchoice_electricity_consumption_total for domain sensor with platform greenchoice
Error adding entity sensor.greenchoice_electricity_return_high for domain sensor with platform greenchoice
Error adding entity sensor.greenchoice_electricity_return_low for domain sensor with platform greenchoice
Error adding entity sensor.greenchoice_electricity_return_total for domain sensor with platform greenchoice
Error adding entity sensor.greenchoice_gas_consumption for domain sensor with platform greenchoice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 657, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 660, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    raise ValueError(
ValueError: Sensor sensor.greenchoice_electricity_consumption_high has device class 'energy', state class 'total' unit 'kWh' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)
```

My best guess is that these errors appear because I disabled the [automatic remote meter reading by Enexis](https://www.enexis.nl/meter/slimme-meter/uw-privacy-en-gegevens). This would also mean that both Enexis and GreenChoice don't receive my meter readings (I'm only interested in the tariffs).

**Comment by eelcohn** [comment]
Changing line 157 in `/custom_components/greenchoice/sensor.py` to:
```
        self._measurement_date = api_result[self._measurement_date_key] if self._measurement_date_key in api_result else None
```
...seems to fix the first error.

**Comment by eelcohn** [comment]
And changing line 145 in `/custom_components/greenchoice/sensor.py` to:
```
        self._attr_native_value = None
```
...seems to fix the second error.

**Comment by barisdemirdelen** [comment]
Thank you, should be fixed in master
