### ISSUE TITLE
Internal Server Error, did something change?

### ISSUE THREAD

**Issue by BramNH** [barisdemirdelen/homeassistant-greenchoice#20]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/greenchoice/auth.py:107
integration: greenchoice (documentation, issues)
First occurred: October 22, 2024 at 9:59:39 PM (1 occurrences)
Last logged: October 22, 2024 at 9:59:39 PM

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/sensor.py", line 105, in setup_platform
    greenchoice_api = GreenchoiceApi(username, password)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/api.py", line 33, in __init__
    self.auth = Auth(BASE_URL, username, password)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/auth.py", line 21, in __init__
    self.session = self.refresh_session()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/auth.py", line 116, in refresh_session
    self._activate_session()
  File "/config/custom_components/greenchoice/auth.py", line 107, in _activate_session
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://mijn.greenchoice.nl/

**Comment by BramNH** [comment]
Nevermind, seems to have been a temporary thing. But had to restart HA since it's setup via configuration.yaml. Might be handy to be able to reload the integration when entities are unavailable.
