### ISSUE TITLE
Configuring a "Future" account causes sensor startup to crash

### ISSUE THREAD

**Issue by skyegecko** [barisdemirdelen/homeassistant-greenchoice#9]
I have a brand new GreenChoice account, and the start date for my contract is in the future. I thought I'd get this integration set up in the meantime but unfortunately it crashes during HASS startup. Logs:

<details>

```
home-assistant-1  | 2024-06-24T17:44:45.202564740Z 2024-06-24 19:44:45.136 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up greenchoice platform for sensor
home-assistant-1  | 2024-06-24T17:44:45.202599962Z Traceback (most recent call last):
home-assistant-1  | 2024-06-24T17:44:45.202605632Z   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
home-assistant-1  | 2024-06-24T17:44:45.202610535Z     await asyncio.shield(awaitable)
home-assistant-1  | 2024-06-24T17:44:45.202621883Z   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
home-assistant-1  | 2024-06-24T17:44:45.202625778Z     result = self.fn(*self.args, **self.kwargs)
home-assistant-1  | 2024-06-24T17:44:45.202635543Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-1  | 2024-06-24T17:44:45.202637627Z   File "/config/custom_components/greenchoice/sensor.py", line 99, in setup_platform
home-assistant-1  | 2024-06-24T17:44:45.202639785Z     throttled_api_update(greenchoice_api)
home-assistant-1  | 2024-06-24T17:44:45.202641782Z   File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 191, in wrapper
home-assistant-1  | 2024-06-24T17:44:45.202643853Z     result = method(*args, **kwargs)
home-assistant-1  | 2024-06-24T17:44:45.202645851Z              ^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-1  | 2024-06-24T17:44:45.202647823Z   File "/config/custom_components/greenchoice/sensor.py", line 116, in throttled_api_update
home-assistant-1  | 2024-06-24T17:44:45.202649964Z     api_result = api.update()
home-assistant-1  | 2024-06-24T17:44:45.202651914Z                  ^^^^^^^^^^^^
home-assistant-1  | 2024-06-24T17:44:45.202653848Z   File "/config/custom_components/greenchoice/api.py", line 190, in update
home-assistant-1  | 2024-06-24T17:44:45.202655897Z     self.update_usage_values(self.result)
home-assistant-1  | 2024-06-24T17:44:45.202657936Z   File "/config/custom_components/greenchoice/api.py", line 209, in update_usage_values
home-assistant-1  | 2024-06-24T17:44:45.202659995Z     products = monthly_values["model"]["productenOpnamesModel"]
home-assistant-1  | 2024-06-24T17:44:45.202662214Z                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-1  | 2024-06-24T17:44:45.202664217Z TypeError: 'NoneType' object is not subscriptable

```

</details>

I'm going to grab some food first but after dinner I'll try accessing the API with Postman to see what objects exactly I'm getting back.

### Update:

When sending "OpnamesOphalen" I received:

```json
{
    "correlationId": "<secretguid>xxxx",
    "klantnummer": <secretint>xxxx,
    "overeenkomstId": <secretint>xxxx,
    "model": null,
    "success": false,
    "error": "Op dit moment leveren we nog niet. Probeer het later nogmaals.",
    "heeftOpnameRegistrerenRecht": true
}
```

When sending "GetTariefOvereenkomst" I seem to get a normal response, including my upcoming all-in tariffs. So I think there is an opportunity for this integration to be able to retrieve tariffs even when there's no usage data available.

**Comment by barisdemirdelen** [comment]
Hello, is this still an issue for you? We are not using microbus requests anymore for these queries

**Comment by skyegecko** [comment]
Hi, no my contract has started now so I don't have an easy of retesting this. Thanks for responding.
